4/19/2026
advance programming for data scientist

numpy - pandas - matplotlib - seaborn

In [8]:
pip show numpy

Name: numpy
Version: 2.4.4
Summary: Fundamental package for array computing in Python
Home-page: https://numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License-Expression: BSD-3-Clause AND 0BSD AND MIT AND Zlib AND CC0-1.0
Location: C:\Users\AhadS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages
Requires: 
Required-by: contourpy, matplotlib, pandas, seaborn
Note: you may need to restart the kernel to use updated packages.


In [14]:
import pandas as pd
import matplotlib as mp
import seaborn as sn
print(pd.__version__)
print(mp.__version__)
print(sn.__version__)

3.0.2
3.10.8
0.13.2


In [7]:
import numpy as np

In [17]:
arr = np.array([1,2,3,4,5,7])
arr

array([1, 2, 3, 4, 5, 7])

In [23]:
#2d array
arr2 = np.array([[1,2,3,4,7],
                 [9,8,7,5,5]] )
arr2

array([[1, 2, 3, 4, 7],
       [9, 8, 7, 5, 5]])

In [26]:
l1 = [1,2,4]
arr3 = np.array(l1)
arr3

array([1, 2, 4])

In [46]:
l2 = [[1,2,3],[4,5,6]]
arr4 = np.array(l2)
print( arr4)
print("shape: ",arr4.shape)
print("rows: ",arr4.shape[0])
print("columns: ",arr4.shape[1])
print("type: ",arr4.dtype)

[[1 2 3]
 [4 5 6]]
shape:  (2, 3)
rows:  2
columns:  3
type:  int64


In [59]:
arr5 = np.zeros(19,'int')
print(arr5)
print("shape: ",arr5.shape)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
shape:  (19,)


In [60]:
arr6 = np.ones(20,'int')
print("array of ones: ",arr6)
print("shape: ",arr6.shape)
arr7 = np.ones([5,20],'int')
print("array of ones: ",arr7)
print("shape: ",arr7.shape)

array of ones:  [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
shape:  (20,)
array of ones:  [[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]
shape:  (5, 20)


In [62]:
np.empty(5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [64]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [65]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [73]:
np.arange(0,11,2) #(start,end,step)

array([ 0,  2,  4,  6,  8, 10])

In [85]:
arr8 = np.array([1,2,3])
arr9 = np.array([2,2,2])
print(arr8 * arr9)
print(arr8 - 11)
print(arr8 ** 3)
print("array\n",arr4)
print("transpose\n", arr4.T)

[2 4 6]
[-10  -9  -8]
[ 1  8 27]
array
 [[1 2 3]
 [4 5 6]]
transpose
 [[1 4]
 [2 5]
 [3 6]]


In [88]:
A=np.array([[1,2,3],[4,5,6]])
print(A)
print('\n')
B=np.array([[7,8],[9,10],[11,12]])
print(B)
print('\n')
np.dot(A,B)

[[1 2 3]
 [4 5 6]]


[[ 7  8]
 [ 9 10]
 [11 12]]




array([[ 58,  64],
       [139, 154]])

In [95]:
arr10 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
laste = arr10[arr10.shape[0]-1] #last element 
print(laste)
print(arr10[2:6])

10
[2 3 4 5]


In [114]:
arr11 = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
print(arr11[0:3 , 2:8]) #[rows slice : col slice]

[[2 3 4 5 6 7]
 [2 3 4 5 6 7]
 [2 3 4 5 6 7]]


In [139]:
arr12 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr12[0:5] = 999
print(arr12)
arr13 = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
arr13[:,0:3] = 999
print(arr13)
arr12copy = arr12[6:9].copy()
print(arr12copy)
print(arr13[:,8])
print(arr13[:3, ::2])

[999 999 999 999 999   5   6   7   8   9  10]
[[999 999 999   3   4   5   6   7   8   9  10]
 [999 999 999   3   4   5   6   7   8   9  10]
 [999 999 999   3   4   5   6   7   8   9  10]]
[6 7 8]
[8 8 8]
[[999 999   4   6   8  10]
 [999 999   4   6   8  10]
 [999 999   4   6   8  10]]


In [144]:
arr14 = np.arange(1,13).reshape(4,3) #reshape take array and returns array
print(arr14)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [151]:
arr15 = np.array([1,2,3])
arr16 = np.array([5,6,7])
np.concatenate([arr15,arr16])

array([1, 2, 3, 5, 6, 7])

In [157]:
arr17 = np.array([[0, 1, 2, 3],[ 7, 8, 9, 10],[ 4, 5, 6, 7]])
arr18 = np.array([[0, 1, 2, 3],[ 7, 8, 9, 10],[ 4, 5, 6, 7]])
r = np.concatenate([arr17,arr18], axis=0) #merge in rows when axix = 0 if no axis by defoult its 0
print(r)
r2 = np.concatenate([arr17,arr18], axis=1) #merge in col when axix = 1
print(r2)

[[ 0  1  2  3]
 [ 7  8  9 10]
 [ 4  5  6  7]
 [ 0  1  2  3]
 [ 7  8  9 10]
 [ 4  5  6  7]]
[[ 0  1  2  3  0  1  2  3]
 [ 7  8  9 10  7  8  9 10]
 [ 4  5  6  7  4  5  6  7]]


In [186]:
arr19 = np.arange(16).reshape(4,4)
print(arr19)

upper, lower = np.vsplit(arr19,[2])
print("\n\nvertical split\n",upper)
print("\n",lower)

left, right = np.hsplit(arr19,[2])
print("\n\nhorizantal split\n",left)
print("\n",right)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


vertical split
 [[0 1 2 3]
 [4 5 6 7]]

 [[ 8  9 10 11]
 [12 13 14 15]]


horizantal split
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]

 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [203]:
arr20 = np.arange(1,21).reshape(4,5)
u, d = np.vsplit(arr20,[3])
print(u,"\n\n",d,"\n\n\n")
l, r = np.hsplit(arr20,[1])
print(l,"\n\n")
print(r)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]] 

 [[16 17 18 19 20]] 



[[ 1]
 [ 6]
 [11]
 [16]] 


[[ 2  3  4  5]
 [ 7  8  9 10]
 [12 13 14 15]
 [17 18 19 20]]


In [207]:
arr21 = np.arange(1,21).reshape(4,5)
u, d ,dd = np.vsplit(arr20,[2,3])
print(u,"\n\n",d,"\n\n", dd,"\n\n\n")
l, r = np.hsplit(arr20,[1])
print(l,"\n\n")
print(r)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

 [[11 12 13 14 15]] 

 [[16 17 18 19 20]] 



[[ 1]
 [ 6]
 [11]
 [16]] 


[[ 2  3  4  5]
 [ 7  8  9 10]
 [12 13 14 15]
 [17 18 19 20]]


In [217]:
arr22 = np.arange(1,11,1)
print(arr22,"\n\n")
print("square root: \n",np.sqrt(arr22),"\n\n")
print("exponantioal: \n",np.exp(arr22))


[ 1  2  3  4  5  6  7  8  9 10] 


square root: 
 [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766] 


exponantioal: 
 [2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]


In [228]:
print(np.random.randint(0,100,20))
print(np.random.randn(3)) # normal numbers

[54 31 36 29  9 71 75 81 42 53  5 34 34 39 14 79 86 14 16 71]
[ 1.03479823  1.25864154 -0.34748279]


In [242]:
a = np.random.randint(0,100,10)
b = np.random.randint(0,100,10)
print("array a",a,"\narray b",b,"\n\n")
print("sum of a and b\n", np.add(a,b),"\n\n")
print("max of a and b\n", np.maximum(a,b))

array a [58 54 35 89 41 40 16 50 32 62] 
array b [64 29 98 66 85 15 28 84 88 33] 


sum of a and b
 [122  83 133 155 126  55  44 134 120  95] 


max of a and b
 [64 54 98 89 85 40 28 84 88 62]


In [252]:
a1 = np.random.randint(0,10,5)
b1 = np.random.randint(100,999,5)
condition = np.array([True,True,False,False,True])
ans = np.where(condition,a1,b1)
print("array a: ",a1,"\n\narray b: ",b1,"\n\napplying when: ",ans)

array a:  [1 6 8 8 4] 

array b:  [712 419 570 181 925] 

applying when:  [  1   6 570 181   4]


In [262]:
arr23 = np.random.randint(-100,100,10)
arr24 = np.random.randn(5,5)
print(arr24)
rr = np.where(arr24 <0, 0,arr24) #replace all negatives with zeros
print(rr)
rr1 = np.where(arr23 <0, 0,arr23)
print(rr1)

[[ 0.11698246 -0.6943917   0.65156998 -1.18592076 -0.8607077 ]
 [-1.35465351 -0.3645942  -1.46214811 -1.14133375 -0.16202125]
 [ 1.66245599 -0.35581237  0.03180114  0.33005875  0.69485035]
 [ 0.05508545 -1.47803138 -1.06208029 -0.10515198  0.51246372]
 [-1.65611322 -1.84241319  1.32219648 -1.38173384  0.05618579]]
[[0.11698246 0.         0.65156998 0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [1.66245599 0.         0.03180114 0.33005875 0.69485035]
 [0.05508545 0.         0.         0.         0.51246372]
 [0.         0.         1.32219648 0.         0.05618579]]
[84 37  0 67 45 52 18  0 69 11]


In [265]:
arr25 = np.random.randint(0,100,10)
print(arr25)
print(arr25.sum())

[28 91 72 23 67 24 62 15 18 41]
441


In [292]:
arr26 = np.array([[8,2,3],[2,7,2]])
print(arr26)
print(arr26.sum(0)) #sum on columns
print(arr26.sum(1)) #sum on rows
print(arr26.mean()) #mean
print(arr26.std()) #standard diviation sqrt of var
print(arr26.var()) #variance
a = np.sort(arr26)
print(a)


[[8 2 3]
 [2 7 2]]
[10  9  5]
[13 11]
4.0
2.516611478423583
6.333333333333333
[[2 3 8]
 [2 2 7]]


In [277]:
arr27 = np.array([False,True,True,False])
print(arr27)
print(arr27.any()) #is there at least one true? 
print(arr27.all()) #is all elements are true? 

[False  True  True False]
True
False


In [302]:
countries = np.array(['om','om','om','uae','uae','ksa','kuwite','qatar','kuwite','bahrain'])
print(np.unique(countries))

['bahrain' 'ksa' 'kuwite' 'om' 'qatar' 'uae']
