4/19/2026
advance programming for data scientist

numpy - pandas - matplotlib - seaborn

In [1]:
pip show numpy

Name: numpy
Version: 2.4.4
Summary: Fundamental package for array computing in Python
Home-page: https://numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License-Expression: BSD-3-Clause AND 0BSD AND MIT AND Zlib AND CC0-1.0
Location: C:\Users\AhadS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages
Requires: 
Required-by: contourpy, matplotlib, pandas, seaborn
Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd
import matplotlib as mp
import seaborn as sn
print(pd.__version__)
print(mp.__version__)
print(sn.__version__)

3.0.2
3.10.8
0.13.2


In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5,7])
arr

array([1, 2, 3, 4, 5, 7])

In [5]:
#2d array
arr2 = np.array([[1,2,3,4,7],
                 [9,8,7,5,5]] )
arr2

array([[1, 2, 3, 4, 7],
       [9, 8, 7, 5, 5]])

In [6]:
l1 = [1,2,4]
arr3 = np.array(l1)
arr3

array([1, 2, 4])

In [7]:
l2 = [[1,2,3],[4,5,6]]
arr4 = np.array(l2)
print( arr4)
print("shape: ",arr4.shape)
print("rows: ",arr4.shape[0])
print("columns: ",arr4.shape[1])
print("type: ",arr4.dtype)

[[1 2 3]
 [4 5 6]]
shape:  (2, 3)
rows:  2
columns:  3
type:  int64


In [8]:
arr5 = np.zeros(19,'int')
print(arr5)
print("shape: ",arr5.shape)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
shape:  (19,)


In [9]:
arr6 = np.ones(20,'int')
print("array of ones: ",arr6)
print("shape: ",arr6.shape)
arr7 = np.ones([5,20],'int')
print("array of ones: ",arr7)
print("shape: ",arr7.shape)

array of ones:  [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
shape:  (20,)
array of ones:  [[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]
shape:  (5, 20)


In [10]:
np.empty(5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [13]:
np.arange(0,11,2) #(start,end,step)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
arr8 = np.array([1,2,3])
arr9 = np.array([2,2,2])
print(arr8 * arr9)
print(arr8 - 11)
print(arr8 ** 3)
print("array\n",arr4)
print("transpose\n", arr4.T)

[2 4 6]
[-10  -9  -8]
[ 1  8 27]
array
 [[1 2 3]
 [4 5 6]]
transpose
 [[1 4]
 [2 5]
 [3 6]]


In [15]:
A=np.array([[1,2,3],[4,5,6]])
print(A)
print('\n')
B=np.array([[7,8],[9,10],[11,12]])
print(B)
print('\n')
np.dot(A,B)

[[1 2 3]
 [4 5 6]]


[[ 7  8]
 [ 9 10]
 [11 12]]




array([[ 58,  64],
       [139, 154]])

In [16]:
arr10 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
laste = arr10[arr10.shape[0]-1] #last element 
print(laste)
print(arr10[2:6])

10
[2 3 4 5]


In [17]:
arr11 = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
print(arr11[0:3 , 2:8]) #[rows slice : col slice]

[[2 3 4 5 6 7]
 [2 3 4 5 6 7]
 [2 3 4 5 6 7]]


In [18]:
arr12 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr12[0:5] = 999
print(arr12)
arr13 = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
arr13[:,0:3] = 999
print(arr13)
arr12copy = arr12[6:9].copy()
print(arr12copy)
print(arr13[:,8])
print(arr13[:3, ::2])

[999 999 999 999 999   5   6   7   8   9  10]
[[999 999 999   3   4   5   6   7   8   9  10]
 [999 999 999   3   4   5   6   7   8   9  10]
 [999 999 999   3   4   5   6   7   8   9  10]]
[6 7 8]
[8 8 8]
[[999 999   4   6   8  10]
 [999 999   4   6   8  10]
 [999 999   4   6   8  10]]


In [19]:
arr14 = np.arange(1,13).reshape(4,3) #reshape take array and returns array
print(arr14)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [20]:
arr15 = np.array([1,2,3])
arr16 = np.array([5,6,7])
np.concatenate([arr15,arr16])

array([1, 2, 3, 5, 6, 7])

In [21]:
arr17 = np.array([[0, 1, 2, 3],[ 7, 8, 9, 10],[ 4, 5, 6, 7]])
arr18 = np.array([[0, 1, 2, 3],[ 7, 8, 9, 10],[ 4, 5, 6, 7]])
r = np.concatenate([arr17,arr18], axis=0) #merge in rows when axix = 0 if no axis by defoult its 0
print(r)
r2 = np.concatenate([arr17,arr18], axis=1) #merge in col when axix = 1
print(r2)

[[ 0  1  2  3]
 [ 7  8  9 10]
 [ 4  5  6  7]
 [ 0  1  2  3]
 [ 7  8  9 10]
 [ 4  5  6  7]]
[[ 0  1  2  3  0  1  2  3]
 [ 7  8  9 10  7  8  9 10]
 [ 4  5  6  7  4  5  6  7]]


In [22]:
arr19 = np.arange(16).reshape(4,4)
print(arr19)

upper, lower = np.vsplit(arr19,[2])
print("\n\nvertical split\n",upper)
print("\n",lower)

left, right = np.hsplit(arr19,[2])
print("\n\nhorizantal split\n",left)
print("\n",right)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


vertical split
 [[0 1 2 3]
 [4 5 6 7]]

 [[ 8  9 10 11]
 [12 13 14 15]]


horizantal split
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]

 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [23]:
arr20 = np.arange(1,21).reshape(4,5)
u, d = np.vsplit(arr20,[3])
print(u,"\n\n",d,"\n\n\n")
l, r = np.hsplit(arr20,[1])
print(l,"\n\n")
print(r)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]] 

 [[16 17 18 19 20]] 



[[ 1]
 [ 6]
 [11]
 [16]] 


[[ 2  3  4  5]
 [ 7  8  9 10]
 [12 13 14 15]
 [17 18 19 20]]


In [24]:
arr21 = np.arange(1,21).reshape(4,5)
u, d ,dd = np.vsplit(arr20,[2,3])
print(u,"\n\n",d,"\n\n", dd,"\n\n\n")
l, r = np.hsplit(arr20,[1])
print(l,"\n\n")
print(r)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

 [[11 12 13 14 15]] 

 [[16 17 18 19 20]] 



[[ 1]
 [ 6]
 [11]
 [16]] 


[[ 2  3  4  5]
 [ 7  8  9 10]
 [12 13 14 15]
 [17 18 19 20]]


In [25]:
arr22 = np.arange(1,11,1)
print(arr22,"\n\n")
print("square root: \n",np.sqrt(arr22),"\n\n")
print("exponantioal: \n",np.exp(arr22))


[ 1  2  3  4  5  6  7  8  9 10] 


square root: 
 [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766] 


exponantioal: 
 [2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]


In [26]:
print(np.random.randint(0,100,20))
print(np.random.randn(3)) # normal numbers

[73  9 94 84 51 33 18 48 98 95 49 92 69  2 39 31 71 94 96 98]
[-0.96307342 -0.26072495  0.85338749]


In [27]:
a = np.random.randint(0,100,10)
b = np.random.randint(0,100,10)
print("array a",a,"\narray b",b,"\n\n")
print("sum of a and b\n", np.add(a,b),"\n\n")
print("max of a and b\n", np.maximum(a,b))

array a [ 6 57 37 77 60 87 29 52 34 72] 
array b [14 95  4 61 77 24 38  8 43 26] 


sum of a and b
 [ 20 152  41 138 137 111  67  60  77  98] 


max of a and b
 [14 95 37 77 77 87 38 52 43 72]


In [28]:
a1 = np.random.randint(0,10,5)
b1 = np.random.randint(100,999,5)
condition = np.array([True,True,False,False,True])
ans = np.where(condition,a1,b1)
print("array a: ",a1,"\n\narray b: ",b1,"\n\napplying when: ",ans)

array a:  [2 5 0 4 0] 

array b:  [722 768 350 484 310] 

applying when:  [  2   5 350 484   0]


In [29]:
arr23 = np.random.randint(-100,100,10)
arr24 = np.random.randn(5,5)
print(arr24)
rr = np.where(arr24 <0, 0,arr24) #replace all negatives with zeros
print(rr)
rr1 = np.where(arr23 <0, 0,arr23)
print(rr1)

[[-0.38240711  0.79143836  0.48398652 -1.21440576 -0.25001925]
 [-0.68930772 -1.05696826  0.66237132 -0.03154534  0.97918201]
 [-0.70746917  0.86161807 -0.45560827  0.98571469 -0.02110564]
 [ 0.64828415 -0.87506325  1.25153654 -0.3643536  -1.035408  ]
 [-1.57970516 -1.67779084 -1.95278505 -1.65361954 -0.4819258 ]]
[[0.         0.79143836 0.48398652 0.         0.        ]
 [0.         0.         0.66237132 0.         0.97918201]
 [0.         0.86161807 0.         0.98571469 0.        ]
 [0.64828415 0.         1.25153654 0.         0.        ]
 [0.         0.         0.         0.         0.        ]]
[ 0 72  0 46 24  0  0  0  0  0]


In [30]:
arr25 = np.random.randint(0,100,10)
print(arr25)
print(arr25.sum())

[34 77 53 41 33 91 30 60 52 33]
504


In [31]:
arr26 = np.array([[8,2,3],[2,7,2]])
print(arr26)
print(arr26.sum(0)) #sum on columns
print(arr26.sum(1)) #sum on rows
print(arr26.mean()) #mean
print(arr26.std()) #standard diviation sqrt of var
print(arr26.var()) #variance
a = np.sort(arr26)
print(a)


[[8 2 3]
 [2 7 2]]
[10  9  5]
[13 11]
4.0
2.516611478423583
6.333333333333333
[[2 3 8]
 [2 2 7]]


In [32]:
arr27 = np.array([False,True,True,False])
print(arr27)
print(arr27.any()) #is there at least one true? 
print(arr27.all()) #is all elements are true? 

[False  True  True False]
True
False


In [33]:
countries = np.array(['om','om','om','uae','uae','ksa','kuwite','qatar','kuwite','bahrain'])
print(np.unique(countries))

['bahrain' 'ksa' 'kuwite' 'om' 'qatar' 'uae']


In [34]:
#columns = [age, heart_rate, cholesterol, blood_pressure]
import numpy as np
patients_data = np.array([
[45, 80, 200, 120],
[60, 90, 240, 140],
[30, 70, 180, 110],
[50, 85, 220, 130],
[65, 95, 260, 150]
])

#shape of dataset
print(patients_data.shape) #(5,4)
# how many patient 
print(patients_data.shape[0]) #5
# how many features
print(patients_data.shape[1]) #4

(5, 4)
5
4


In [35]:
#the data of the first patient
print(patients_data[0])
#all ages
print("\n",patients_data[:,:1])
#all blood pressure values
print("\n",patients_data[:,3:])

[ 45  80 200 120]

 [[45]
 [60]
 [30]
 [50]
 [65]]

 [[120]
 [140]
 [110]
 [130]
 [150]]


In [36]:
#ave ages
totalages = np.sum(patients_data[:,:1]) 
numberages = patients_data.shape[1]
aveages = totalages / numberages
print("\n",aveages)


 62.5


In [37]:
#maximum heart rate
heartRate = patients_data[:,1:2]
print(np.max(heartRate))

95


In [38]:
#minimum cholesterol leve
cholesterol = patients_data[:,2:3]
print(np.min(cholesterol))

180


In [39]:
#blood pressure > 130
pressure = patients_data[:,3:]
print(pressure > 130)

[[False]
 [ True]
 [False]
 [False]
 [ True]]


In [40]:
#cholesterol ≥ 240
cholesterol = patients_data[:,2:3]
print(cholesterol >= 240)

[[False]
 [ True]
 [False]
 [False]
 [ True]]


In [41]:
#older than 50
age = patients_data[:,:1]
print(age >50)

[[False]
 [ True]
 [False]
 [False]
 [ True]]


In [42]:
#high-risk patients
highP = pressure> 140
highC = cholesterol >240
print(highP * highC)

[[False]
 [False]
 [False]
 [False]
 [ True]]


In [43]:
total1 = 0
c1 = 0
total2 = 0
c2 = 0
ageHeart = patients_data[:,:2]
for i in range(patients_data.shape[0]):
    if ageHeart[:,0:1][i] >= 50:
        total1 += ageHeart[:,1:2][i]
        c1 += 1
        ave1 = total1 / c1
    else:
        total2 += ageHeart[:,1:2][i]
        c2 += 1
        ave2 = total2 / c2
        

print(ave1)
print(ave2)
if ave1 > ave2:
    print("above 50 have more heart rate")
else:
    print("under 50 have more heart rate")

[90.]
[75.]
above 50 have more heart rate


In [44]:
pressure = patients_data[:,3:]
print(pressure)
maxP = np.max(pressure)

heartRate = patients_data[:,1:2]
print(heartRate)
minH = np.min(heartRate)

for i in range(patients_data.shape[0]):
    if pressure[i] == maxP:
        print("patient at index ",i,"highst pressure (",maxP,")")
    if heartRate[i] == minH:
        print("patient at index ",i,"lowest heart rate (",minH,")")

[[120]
 [140]
 [110]
 [130]
 [150]]
[[80]
 [90]
 [70]
 [85]
 [95]]
patient at index  2 lowest heart rate ( 70 )
patient at index  4 highst pressure ( 150 )


In [45]:
total1 = 0
c1 = 0
total2 = 0
c2 = 0
pressure = patients_data[:,3:]
age = patients_data[:,:1]
for i in range(patients_data.shape[0]):
    if age[i] >= 50:
        total1 += pressure[i]
        c1 += 1
        ave1 = total1 / c1
    else:
        total2 += pressure[i]
        c2 += 1
        ave2 = total2 / c2
        

print(ave1)
print(ave2)
if ave1 > ave2:
    print("older people have higher blood pressure")
else:
    print("younger people have higher blood pressuree")

[140.]
[115.]
older people have higher blood pressure


4\20\2026

In [55]:
patientID = np.array([101,102,103,104,105])
heartRate = np.array([72,110,95,130,88])
status = np.where(heartRate > 100, "Critical", "Stable")

print("patient ID:   ", patientID)
print("heart rate:   ", heartRate)
print("Status: ", status)

arr28 = np.array([patientID,heartRate,status]).T
print("\n\n",arr28)

patient ID:    [101 102 103 104 105]
heart rate:    [ 72 110  95 130  88]
Status:  ['Stable' 'Critical' 'Stable' 'Critical' 'Stable']


 [['101' '72' 'Stable']
 ['102' '110' 'Critical']
 ['103' '95' 'Stable']
 ['104' '130' 'Critical']
 ['105' '88' 'Stable']]


In [61]:
temp = np.array([30,0,73,0,67,7,2,0])

condition = temp != 0 
print(condition)
filtered = temp[condition]
print("non zeros",filtered)
avetemp = filtered.mean()
print("average",avetemp)
cleanedtemp = np.where(temp == 0, avetemp, temp)
print("original",temp)
print("cleaned",cleanedtemp)

[ True False  True False  True  True  True False]
non zeros [30 73 67  7  2]
average 35.8
original [30  0 73  0 67  7  2  0]
cleaned [30.  35.8 73.  35.8 67.   7.   2.  35.8]


In [65]:
temp = np.array([30,0,73,0,67,7,2,0,38,40])

condition = temp > 37 
print(condition)
filtered = temp[condition]
print("larger than 37",filtered)
avetemp = filtered.mean()
print("average",avetemp)

[False False  True False  True False False False  True  True]
larger than 37 [73 67 38 40]
average 54.5


In [70]:
age = np.array([20,38,74,17,90])
bp = np.array([120,140,140,170,190])
st = np.where((age > 60) | (bp > 140), "critical","normal")
print(st)


['normal' 'normal' 'critical' 'critical' 'critical']


In [80]:
salaries = np.array([100,200,300,400,500,600,700,800,900,1000])
condition = salaries >= 500
b = np.where(condition, (salaries + 100), (salaries + 50))
print("salaries with bonus: ",b)

salaries with bonus:  [ 150  250  350  450  600  700  800  900 1000 1100]


In [92]:
marks = np.array([100,20,30,90,70,80,40,98])
grade = np.where(marks > 85,
                 np.where(marks > 95, "A+","A") ,
                 np.where(marks > 70, "B","C"))
print(grade)

['A+' 'C' 'C' 'A' 'C' 'B' 'C' 'A+']


In [97]:
purches = np.array([100,299,29,63,97,77,10])
price = np.where(purches>=100,purches*0.8,purches*0.9)
print("prices after discount: ",price)

prices after discount:  [ 80.  239.2  26.1  56.7  87.3  69.3   9. ]


In [104]:
hr = np.array([20,40,90,122,199,319])
o = np.array([90,97,95,70,17,80])
emergency = np.where((hr>120) & (o<90),"emergency","normal")
print(emergency)


['normal' 'normal' 'normal' 'emergency' 'emergency' 'emergency']


In [119]:
arr29 = np.linspace(1, 10, num=5)
dim = arr29.ndim
print(" array using line space:",arr29,"\n\n","dimintion of array using ndim: ",dim)

 array using line space: [ 1.    3.25  5.5   7.75 10.  ] 

 dimintion of array using ndim:  1


pandas

In [124]:
import pandas as pd
print(pd.__version__)

3.0.2


In [156]:
l = [1,2,3,4]
series = pd.Series(l)
print(series)

seriesIndex = pd.Series(l, index=['a','b','c','d'])
seriesIndex.index.name = "indexed series" #name of indexes
print()
print(seriesIndex)
print("name :",seriesIndex.index.name)
seriesIndex.index = [1,2,3,4]
print()
print(seriesIndex)
print(seriesIndex.values) #array
print(seriesIndex.values.max())
print(np.mean(seriesIndex.values))
print(seriesIndex.index)
seriesIndex.name = "series" #name of series
print("name :",seriesIndex.name)

0    1
1    2
2    3
3    4
dtype: int64

indexed series
a    1
b    2
c    3
d    4
dtype: int64
name : indexed series

1    1
2    2
3    3
4    4
dtype: int64
[1 2 3 4]
4
2.5
Index([1, 2, 3, 4], dtype='int64')
name : series
1


In [133]:
dataframe = pd.DataFrame(l)
print(dataframe)

   0
0  1
1  2
2  3
3  4
4  5
5  6


In [168]:
print(seriesIndex)
print("\n")
print(seriesIndex[1])
print("\n")
print(seriesIndex<3)
print("\n\n")
print(seriesIndex[seriesIndex<3])
print("\n")
print(2 in seriesIndex)

1    1
2    2
3    3
4    4
Name: series, dtype: int64


1


1     True
2     True
3    False
4    False
Name: series, dtype: bool



1    1
2    2
Name: series, dtype: int64


True


In [171]:
l = [1,2,3,4]
s = pd.Series(l)
s = pd.Series(l, index=['aa','bb','cc','dd'])
dic = s.to_dict()
print(dic)
ser = pd.Series(dic)
print(ser)

{'aa': 1, 'bb': 2, 'cc': 3, 'dd': 4}
aa    1
bb    2
cc    3
dd    4
dtype: int64


In [192]:
countriesPop = pd.Series([
8700000,
4300000,
3000000,
2100000,
np.nan],index = ['China','Germany','Japan','USA',"Oman"])
countriesPop.name = "countriesPop"
countriesPop

China      8700000.0
Germany    4300000.0
Japan      3000000.0
USA        2100000.0
Oman             NaN
Name: countriesPop, dtype: float64

In [181]:
print(pd.isnull(countriesPop))
print("sum of nulls",pd.isnull(countriesPop).sum())

China      False
Germany    False
Japan      False
USA        False
Oman        True
Name: countriesPop, dtype: bool
sum of nulls 1


In [183]:
print(pd.notnull(countriesPop))
print("sum of not nulls",pd.notnull(countriesPop).sum())

China       True
Germany     True
Japan       True
USA         True
Oman       False
Name: countriesPop, dtype: bool
sum of not nulls 4


In [194]:
countriesPop1 = pd.Series([
8700000,
4300000,
3000000,
2100000,
5000000], index = ['China','Germany','Japan','USA',"Oman"])

In [195]:
countriesPop1 + countriesPop

China      17400000.0
Germany     8600000.0
Japan       6000000.0
USA         4200000.0
Oman              NaN
dtype: float64

In [198]:
s = pd.Series({"math" : 90, "english" : 80, "science" : 70})
print(s[s > 70])

math       90
english    80
dtype: int64


In [207]:
s = pd.Series([10,20,30,None,30,None])

print(s.isna().sum())

ave = s.mean()

s = s.fillna(ave)
print(s)

2
0    10.0
1    20.0
2    30.0
3    22.5
4    30.0
5    22.5
dtype: float64


In [216]:
names = pd.Series(['aaaa','bbb','cccc','ddddd'])
names.str.upper()
print()
print(names[names.str.len() > 3])


0     aaaa
2     cccc
3    ddddd
dtype: str


In [220]:
s = pd.Series([1,3,5,6],index = ['a','b','c','d'])
print(s)

s.rename(index={'a':'aa'}, inplace = True) #inplace apply changes
print(s)

s['e'] = 2 #adding new value
print(s)

a    1
b    3
c    5
d    6
dtype: int64
aa    1
b     3
c     5
d     6
dtype: int64
aa    1
b     3
c     5
d     6
e     2
dtype: int64


In [229]:
s = pd.Series([1,9,6,3,8,4])
s.sort_values(inplace = True)
print(s)
s.sort_index()

0    1
3    3
5    4
2    6
4    8
1    9
dtype: int64


0    1
1    9
2    6
3    3
4    8
5    4
dtype: int64

In [231]:
s = pd.Series([1,1,1,5,5,6,3,1,4,5])
print(s.value_counts())

1    4
5    3
6    1
3    1
4    1
Name: count, dtype: int64


In [234]:
s1 = pd.Series([10, 20, 30])
s2 = pd.Series([15, 15, 35])
print(s1==s2)
print()
print(s1<s2)

0    False
1    False
2    False
dtype: bool

0     True
1    False
2     True
dtype: bool


In [235]:
sales = pd.Series([200, 450, 300, 150, 500],
                  index=["Mon", "Tue", "Wed", "Thu", "Fri"])

# Total sales
print("Total:", sales.sum())

# Average sales
print("Average:", sales.mean())

# Max sales day
print("Highest day:", sales.idxmax())

# Sales > 300
print("Days with sales > 300:")
print(sales[sales > 300])

Total: 1600
Average: 320.0
Highest day: Fri
Days with sales > 300:
Tue    450
Fri    500
dtype: int64


In [238]:
data = {
'Name': ['Alice', 'Bob', 'Charlie'],
'Age': [24, 27, 22],
'City': ['New York', 'Los Angeles', 'Chicago']
}
df = pd.DataFrame(data)
print(df)

      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago


data expolaration 

In [239]:
df.head(2)

,Name,Age,City
0,Alice,24,New York
1,Bob,27,Los Angeles


In [240]:
df.tail(1)

,Name,Age,City
2,Charlie,22,Chicago


In [241]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str  
 1   Age     3 non-null      int64
 2   City    3 non-null      str  
dtypes: int64(1), str(2)
memory usage: 204.0 bytes


In [242]:
df.describe()

,Age
count,3.000000
mean,24.333333
std,2.516611
min,22.000000
25%,23.000000
50%,24.000000
75%,25.500000
max,27.000000


In [249]:
print(df['Name'])
print()
print(df[['Name','City']])
print()
print(df.iloc[0]) #iloc index
print()
print(df.loc[1]) 

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: str

      Name         City
0    Alice     New York
1      Bob  Los Angeles
2  Charlie      Chicago

Name       Alice
Age           24
City    New York
Name: 0, dtype: object

Name            Bob
Age              27
City    Los Angeles
Name: 1, dtype: object


In [257]:
pip install kagglehub

Note: you may need to restart the kernel to use updated packages.


In [271]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Download latest version
path = kagglehub.dataset_download("sudhirsingh108/data-science-students")

In [272]:
print("Path to dataset files:", path)
file_path = "data_science_student_marks.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "sudhirsingh108/data-science-students",
  file_path,
)

print("First 5 records:", df.head())

Path to dataset files: C:\Users\AhadS\.cache\kagglehub\datasets\sudhirsingh108\data-science-students\versions\1


C:\Users\AhadS\AppData\Local\Temp\ipykernel_20368\51535478.py:5: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(


Download already complete (15497 bytes).
First 5 records:    student_id location  age  sql_marks  excel_marks  python_marks  \
0           4   Sydney   24         95           99            87   
1           5    Tokyo   24         99           95            89   
2           6   Berlin   22         72           70            99   
3           7   London   23         97           90            74   
4           8    Tokyo   22         91           71            79   

   power_bi_marks  english_marks  
0              82             75  
1              86             82  
2              79             77  
3              72             85  
4              80             75  


In [273]:
df

,student_id,location,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
0,4,Sydney,24,95,99,87,82,75
1,5,Tokyo,24,99,95,89,86,82
2,6,Berlin,22,72,70,99,79,77
3,7,London,23,97,90,74,72,85
4,8,Tokyo,22,91,71,79,80,75
...,...,...,...,...,...,...,...,...
492,496,New York,23,71,92,98,78,88
493,497,Los Angeles,20,90,100,90,78,73
494,498,Paris,22,78,80,78,71,70
495,499,Los Angeles,21,96,93,78,78,82


In [289]:
print("|||||"*20)
print("\n\t\t((describe))\n")
print(df.describe())
print("|||||"*20)
print("\n\t\t((head))\n")
print(df.head())
print("|||||"*20)
print("\n\t\t((tail))\n")
print(df.tail())
print("|||||"*20)
print("\n\t\t((info))\n")
print(df.info())

||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||

		((describe))

       student_id         age   sql_marks  excel_marks  python_marks  \
count  497.000000  497.000000  497.000000   497.000000    497.000000   
mean   252.000000   21.380282   84.661972    85.384306     85.388330   
std    143.615807    2.205714    8.745415     8.782497      8.878668   
min      4.000000   18.000000   70.000000    70.000000     70.000000   
25%    128.000000   20.000000   78.000000    78.000000     77.000000   
50%    252.000000   21.000000   85.000000    86.000000     86.000000   
75%    376.000000   23.000000   92.000000    93.000000     94.000000   
max    500.000000   25.000000  100.000000   100.000000    100.000000   

       power_bi_marks  english_marks  
count      497.000000     497.000000  
mean        84.545272      84.824950  
std          8.903066       9.060479  
min         70.000000      70.000000  
25%         77.000000      77.000000  

In [312]:
print("||||||||"*10)
print(df.nunique())

print("||||||||"*10)
print(df['location'].unique())

print("||||||||"*10)
print(df['location'].count())

print("||||||||"*10)
print(df['location'].value_counts())

print("||||||||"*10)
print(df.value_counts())

print("||||||||"*10)
print(df['sql_marks'].mean())

||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
student_id        497
location            9
age                 8
sql_marks          31
excel_marks        31
python_marks       31
power_bi_marks     31
english_marks      31
dtype: int64
||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
<StringArray>
[     'Sydney',       'Tokyo',      'Berlin',      'London',     'Toronto',
   'Melbourne',       'Paris', 'Los Angeles',    'New York']
Length: 9, dtype: str
||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
497
||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
location
Tokyo          60
Los Angeles    60
Melbourne      58
New York       57
Toronto        56
Paris          55
Sydney         53
Berlin         52
London         46
Name: count, dtype: int64
||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
student_id  location     age  sq

In [291]:
print(df.loc[0])

student_id             4
location          Sydney
age                   24
sql_marks             95
excel_marks           99
python_marks          87
power_bi_marks        82
english_marks         75
Name: 0, dtype: object
